# Generated by Django 4.2.3 on 2023-07-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("adddate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Libmembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("grade", models.IntegerField()),
                ("joindate", models.DateField()),
            ],
        ),
    ]
