# Generated by Django 4.2.3 on 2023-07-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oflib", "0002_auto_20230720_1907"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
    ]
