# Generated by Django 4.2.3 on 2023-07-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oflib", "0004_books"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
    ]
