# Generated by Django 4.2.3 on 2023-08-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_post_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="grade",
            field=models.CharField(max_length=200),
        ),
    ]
